version: '3.4'
services:
  postgres:
    container_name: postgres
    restart: 'unless-stopped'
    image: postgres
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=sample__postgres123a
      - POSTGRES_DB=sample
    networks:
      - sample
    ports:
      - '5432:5432'
    expose:
      - 5432
    logging:
      driver: 'json-file'
      options:
        tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
        max-size: '50m'
    volumes:
      - ./Services_Data/sample/postgres:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: '256m'
  redis:
    container_name: redis
    restart: 'unless-stopped'
    image: redis:latest
    command: redis-server --requirepass "sample_123"
    networks:
      - sample
    ports:
      - '6379:6379'
    logging:
      driver: 'json-file'
      options:
        tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
        max-size: '50m'
    volumes:
      - ./Services_Data/sample/redis_data:/data
    deploy:
      resources:
        limits:
          memory: '256m'
  minio:
    image: minio/minio
    container_name: minio
    command: 'server --address ":9000" --console-address ":9001" /data'
    networks:
      - sample
    restart: 'unless-stopped'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./Services_Data/minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  Services_Data: {}

networks:
  sample:
    driver: bridge
